### ISSUE TITLE
老是出错 看下哪里出问题

### ISSUE THREAD

**Issue by ClayMoreBoy** [liuran001/openwrt-packages_action#3]
@liuran001

**Comment by liuran001** [comment]
看到这句话没
`Actions页面报错是正常的，因为只有上游有更新时才能成功上传`
也就是说所有的软件包都已经是最新了，当然不会上传也没必要再去上传

而且我刚刚去看了下你的Action，报错确实是`is up to date`

**Comment by ClayMoreBoy** [comment]
好的 关闭issues
